language: python
os: linux
cache:
    pip: true
matrix:
    include:
        - python: "3.7"
          env: NOXSESSION="tests-3.7"
          dist: xenial
        - python: "3.8"
          env: NOXSESSION="tests-3.8"
        - python: "3.7"
          env: NOXSESSION="lint"
          dist: xenial
install:
    - pip install nox

script:
    - nox --non-interactive --session "$NOXSESSION"
